image: node:latest

cache:
  paths:
    - node_modules/
  key: "$CI_BUILD_REPO"

DeployDev:
  stage: deploy
  only:
    - "Dev"
  allow_failure: false
  script:
    - npm i -g @vue/cli
    - npm install -g firebase-tools
    - npm install
    - npm run build
    - firebase use flexicomms --token $FIREBASE_DEPLOY_KEY
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_DEPLOY_KEY

DeployLive:
  stage: deploy
  only:
    - "Live"
  when: manual
  allow_failure: false
  script:
    - npm i -g @vue/cli
    - npm install -g firebase-tools
    - npm install
    - npm run build
    - firebase use flexi-comms --token $FIREBASE_DEPLOY_KEY
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_DEPLOY_KEY
